INCENTIVE_TYPE = {
    "LOCK2": 3,
    "REDEEM2": 4,
    "BORROW2": 5,
    "REPAY_BORROW2": 6,
    "CLAIM_INCENTIVE": 7,
    "ADD_LIQUIDITY": 8,
    "REMOVE_LIQUIDITY": 9,
    "WITHDRAW_MINE_REWARD": 10
}

BANK_TRANSACTIONS = [
    "LOCK2",
    "REDEEM2",
    "BORROW2",
    "REPAY_BORROW2",
    "CLAIM_INCENTIVE"
]

EXCHANGE_TRANSACTIONS = [
    "ADD_LIQUIDITY",
    "REMOVE_LIQUIDITY",
    "WITHDRAW_MINE_REWARD"
]
