# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x04test\"\x16\n\x05Int32\x12\r\n\x05value\x18\x01 \x01(\x05\"\x16\n\x05Int64\x12\r\n\x05value\x18\x01 \x01(\x03\"\x17\n\x06UInt32\x12\r\n\x05value\x18\x01 \x01(\r\"\x17\n\x06UInt64\x12\r\n\x05value\x18\x01 \x01(\x04\"\x17\n\x06SInt32\x12\r\n\x05value\x18\x01 \x01(\x11\"\x17\n\x06SInt64\x12\r\n\x05value\x18\x01 \x01(\x12\"\x18\n\x07\x46ixed32\x12\r\n\x05value\x18\x01 \x01(\x07\"\x18\n\x07\x46ixed64\x12\r\n\x05value\x18\x01 \x01(\x06\"\x18\n\x07\x42oolean\x12\r\n\x05value\x18\x01 \x01(\x08\"\x18\n\x07Strings\x12\r\n\x05value\x18\x01 \x01(\t\"\x16\n\x05\x42ytes\x12\r\n\x05value\x18\x01 \x01(\x0c\"&\n\x08Repeated\x12\x1a\n\x05value\x18\x01 \x03(\x0b\x32\x0b.test.Int32\"\xd1\x01\n\x07Structs\x12\x16\n\x01\x61\x18\x01 \x01(\x0b\x32\x0b.test.Int32\x12\x17\n\x01\x62\x18\x02 \x01(\x0b\x32\x0c.test.UInt32\x12\x17\n\x01\x63\x18\x03 \x01(\x0b\x32\x0c.test.SInt32\x12\x18\n\x01\x64\x18\x04 \x01(\x0b\x32\r.test.Fixed32\x12\x18\n\x01\x65\x18\x05 \x01(\x0b\x32\r.test.Boolean\x12\x18\n\x01\x66\x18\x06 \x01(\x0b\x32\r.test.Strings\x12\x16\n\x01g\x18\x07 \x01(\x0b\x32\x0b.test.Bytes\x12\x16\n\x01h\x18\x08 \x03(\x0b\x32\x0b.test.Int32b\x06proto3')
)




_INT32 = _descriptor.Descriptor(
  name='Int32',
  full_name='test.Int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Int32.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=42,
)


_INT64 = _descriptor.Descriptor(
  name='Int64',
  full_name='test.Int64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Int64.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=66,
)


_UINT32 = _descriptor.Descriptor(
  name='UInt32',
  full_name='test.UInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.UInt32.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=91,
)


_UINT64 = _descriptor.Descriptor(
  name='UInt64',
  full_name='test.UInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.UInt64.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=116,
)


_SINT32 = _descriptor.Descriptor(
  name='SInt32',
  full_name='test.SInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.SInt32.value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=141,
)


_SINT64 = _descriptor.Descriptor(
  name='SInt64',
  full_name='test.SInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.SInt64.value', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=166,
)


_FIXED32 = _descriptor.Descriptor(
  name='Fixed32',
  full_name='test.Fixed32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Fixed32.value', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=192,
)


_FIXED64 = _descriptor.Descriptor(
  name='Fixed64',
  full_name='test.Fixed64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Fixed64.value', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=218,
)


_BOOLEAN = _descriptor.Descriptor(
  name='Boolean',
  full_name='test.Boolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Boolean.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=244,
)


_STRINGS = _descriptor.Descriptor(
  name='Strings',
  full_name='test.Strings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Strings.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=270,
)


_BYTES = _descriptor.Descriptor(
  name='Bytes',
  full_name='test.Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Bytes.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=294,
)


_REPEATED = _descriptor.Descriptor(
  name='Repeated',
  full_name='test.Repeated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='test.Repeated.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=334,
)


_STRUCTS = _descriptor.Descriptor(
  name='Structs',
  full_name='test.Structs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='test.Structs.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='test.Structs.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='test.Structs.c', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='test.Structs.d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='test.Structs.e', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='test.Structs.f', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='g', full_name='test.Structs.g', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='test.Structs.h', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=546,
)

_REPEATED.fields_by_name['value'].message_type = _INT32
_STRUCTS.fields_by_name['a'].message_type = _INT32
_STRUCTS.fields_by_name['b'].message_type = _UINT32
_STRUCTS.fields_by_name['c'].message_type = _SINT32
_STRUCTS.fields_by_name['d'].message_type = _FIXED32
_STRUCTS.fields_by_name['e'].message_type = _BOOLEAN
_STRUCTS.fields_by_name['f'].message_type = _STRINGS
_STRUCTS.fields_by_name['g'].message_type = _BYTES
_STRUCTS.fields_by_name['h'].message_type = _INT32
DESCRIPTOR.message_types_by_name['Int32'] = _INT32
DESCRIPTOR.message_types_by_name['Int64'] = _INT64
DESCRIPTOR.message_types_by_name['UInt32'] = _UINT32
DESCRIPTOR.message_types_by_name['UInt64'] = _UINT64
DESCRIPTOR.message_types_by_name['SInt32'] = _SINT32
DESCRIPTOR.message_types_by_name['SInt64'] = _SINT64
DESCRIPTOR.message_types_by_name['Fixed32'] = _FIXED32
DESCRIPTOR.message_types_by_name['Fixed64'] = _FIXED64
DESCRIPTOR.message_types_by_name['Boolean'] = _BOOLEAN
DESCRIPTOR.message_types_by_name['Strings'] = _STRINGS
DESCRIPTOR.message_types_by_name['Bytes'] = _BYTES
DESCRIPTOR.message_types_by_name['Repeated'] = _REPEATED
DESCRIPTOR.message_types_by_name['Structs'] = _STRUCTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Int32 = _reflection.GeneratedProtocolMessageType('Int32', (_message.Message,), {
  'DESCRIPTOR' : _INT32,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Int32)
  })
_sym_db.RegisterMessage(Int32)

Int64 = _reflection.GeneratedProtocolMessageType('Int64', (_message.Message,), {
  'DESCRIPTOR' : _INT64,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Int64)
  })
_sym_db.RegisterMessage(Int64)

UInt32 = _reflection.GeneratedProtocolMessageType('UInt32', (_message.Message,), {
  'DESCRIPTOR' : _UINT32,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.UInt32)
  })
_sym_db.RegisterMessage(UInt32)

UInt64 = _reflection.GeneratedProtocolMessageType('UInt64', (_message.Message,), {
  'DESCRIPTOR' : _UINT64,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.UInt64)
  })
_sym_db.RegisterMessage(UInt64)

SInt32 = _reflection.GeneratedProtocolMessageType('SInt32', (_message.Message,), {
  'DESCRIPTOR' : _SINT32,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.SInt32)
  })
_sym_db.RegisterMessage(SInt32)

SInt64 = _reflection.GeneratedProtocolMessageType('SInt64', (_message.Message,), {
  'DESCRIPTOR' : _SINT64,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.SInt64)
  })
_sym_db.RegisterMessage(SInt64)

Fixed32 = _reflection.GeneratedProtocolMessageType('Fixed32', (_message.Message,), {
  'DESCRIPTOR' : _FIXED32,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Fixed32)
  })
_sym_db.RegisterMessage(Fixed32)

Fixed64 = _reflection.GeneratedProtocolMessageType('Fixed64', (_message.Message,), {
  'DESCRIPTOR' : _FIXED64,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Fixed64)
  })
_sym_db.RegisterMessage(Fixed64)

Boolean = _reflection.GeneratedProtocolMessageType('Boolean', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEAN,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Boolean)
  })
_sym_db.RegisterMessage(Boolean)

Strings = _reflection.GeneratedProtocolMessageType('Strings', (_message.Message,), {
  'DESCRIPTOR' : _STRINGS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Strings)
  })
_sym_db.RegisterMessage(Strings)

Bytes = _reflection.GeneratedProtocolMessageType('Bytes', (_message.Message,), {
  'DESCRIPTOR' : _BYTES,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Bytes)
  })
_sym_db.RegisterMessage(Bytes)

Repeated = _reflection.GeneratedProtocolMessageType('Repeated', (_message.Message,), {
  'DESCRIPTOR' : _REPEATED,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Repeated)
  })
_sym_db.RegisterMessage(Repeated)

Structs = _reflection.GeneratedProtocolMessageType('Structs', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Structs)
  })
_sym_db.RegisterMessage(Structs)


# @@protoc_insertion_point(module_scope)
